# Generated by Django 3.2.6 on 2021-09-11 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 12, 5, 50, 460931)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('OPERADOR_IDENTIDAD', 'operador_identidad'), ('OPERADOR_INVERSO', 'operador_inverso'), ('OPERADOR_UMBRAL', 'operador_umbral'), ('OPERADOR_UMBRAL_INVERSO', 'operador_umbral_inverso'), ('OPERADOR_UMBRAL_BINARIO', 'operador_umbral_binario'), ('OPERADOR_UMBRAL_BINARIO_INVERSO', 'operador_umbral_binario_inverso'), ('OPERADOR_ESCALA_GRISES', 'operador_escala_grises'), ('OPERADOR_ESCALA_GRISES_INVERTIDO', 'operador_escala_grises_invertido'), ('OPERADOR_EXTENSION', 'operador_extension'), ('OPERADOR_REDUCCION_GRISES', 'operador_reduccion_grises')], default='OPERADOR_IDENTIDAD', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
