# Generated by Django 3.2.6 on 2021-09-25 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210911_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='edge')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 18, 26, 791179))),
                ('action', models.CharField(choices=[('OPERADOR_ROBERTS', 'operador_roberts'), ('OPERADOR_PREWITT', 'operador_prewitt'), ('OPERADOR_SOBEL', 'operador_sobel'), ('OPERADOR_CANNY', 'operador_canny')], default='OPERADOR_ROBERTS', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 18, 26, 790180)),
        ),
    ]
