# Generated by Django 3.2.6 on 2021-09-25 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210925_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatoredge',
            old_name='image',
            new_name='imageoperator',
        ),
        migrations.AlterField(
            model_name='operatoredge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 41, 43, 49067)),
        ),
        migrations.AlterField(
            model_name='upload',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 41, 43, 47564)),
        ),
    ]
